### PR TITLE
add WithInsecure client option

### LINKED ISSUE #19: Support insecure connections
In order to connect to a local fake server for testing, I'd like to use the grpc.WithInsecure() dial option. This isn't currently possible with gax.

### PR DESCRIPTION
**Pull request by jba**
Fixes #19

### CODE REVIEW

**Comment by jba** [comment]
@saicheems @jmuk @vchudnov-g

**Comment by jmuk** [comment]
In Python, we do allow the channel credential object as an optional parameter.  Can we do the similar way, like WithChannelCredentials or WithGrpcDialOptions?  Then, the users can customize it as they like -- Insecure or custom credentials or whatever.

**Comment by jba** [comment]
Go gGRPC is more complicated that you describe: there are separate options
for insecure, transport creds (TLS), and per-RPC creds (OAuth). Gax
simplifies the last two by using defaults for everything except the scopes.
It should probably allow more possibilities.

I don't know enough about auth to know what the right design is. But I
don't want to block on a long discussion because I need WithInsecure to
write tests for my client now.

**Comment by saicheems** [comment]
One alternative is to add a `ClientOption` called `WithDialOption` and pass custom auth that way. We can also generate default params and avoid any specific auth code in gax.

We don't need to block on it, but if this sounds like a reasonable approach I'll track it with an issue and implement later.

LGTM otherwise.

**Pull request merged**
