### PR TITLE
Add Bundler

### PR DESCRIPTION
**Pull request by jba**
@saicheems @jmuk  I had already written similar code for the logging client, so I thought I would go ahead and write a bundler for gax-golang.

@mcgreevy Will this be useful for pubsub?

### CODE REVIEW

**Comment by saicheems** [comment]
I think it looks good, maybe hold off on others.

Unrelated: do you think it makes sense to do something like this for the page streaming iterator as well? If we can separate the logic into gax then it's testable

also @pongad @vchudnov-g

**Comment by jba** [comment]
Maybe like this? (Compiles, but untested.)

[main.go.txt](https://github.com/googleapis/gax-golang/files/280670/main.go.txt)

**Comment by saicheems** [comment]
Something to consider:

the bundling routine should be able to group requests by some set of fields, and demultiplex by another.
https://github.com/googleapis/toolkit/blob/master/src/test/java/com/google/api/codegen/testdata/python_library.baseline#L94
https://github.com/googleapis/gax-python/blob/master/google/gax/__init__.py#L248

This function combines the `books` field of incoming requests if they have the same `edition` and `shelf.name`, and separates responses if they have different `book_names`.

**Comment by saicheems** [comment]
I'm not actually sure how to do half of this

To split requests on discriminator fields...
Have structs containing the values and use them as map keys?

So
```
type Discriminator struct {
    Edition string
    ShelfName string
}
...
map[Descriminator][]*Book
```

But it could fall apart if one of the discriminator resources is a proto message (pointer).

For the subresponse field, presumably a new response object for each element in the array - this could alleviate @mcgreevy 's concern regarding the pubsub response

**Comment by jba** [comment]
I wouldn't add either of these things to the code I wrote. It's complicated
enough already.

On the request side, I would do something like you suggest: make map keys
from the discriminator fields, but have each key point to a separate
*Bundler. Doing that automatically for Go is hard, because as you mention,
not everything can be a map key, or the right kind of key.

I don't really understand the feature that groups responses. Why do you
need that?

**Comment by saicheems** [comment]
Maybe @tbetbetbe can chime in on that? I'm not immediately sure.

Mapping to separate Bundlers is possible, but depending on how many unique topics the user sends in there the client could be holding on to a variety. I guess there's no getting around that. Responses would have to be retrieved by iterating through each held Bundler, and there would be several error callbacks...

At least I think we can force the client to only provide a primitive type as a discriminator. I'm not sure of other APIs, but at least publisher only discriminates on `topic`

**Comment by mcgreevy** [comment]
The grouping of requests and responses seems like a lot of effort for marginal benefit. The existing hand-written libraries that might use this (pubsub and logging) are already designed in such a way that this grouping will happen naturally: the Logger from the logging already logs to a particular log, and the pubsub client has Topic.Publish, which naturally groups messages by topic.  I'd suggest holding off on generating code for grouping until there's a demonstrated need.

**Comment by saicheems** [comment]
Making sure I'm on the same page:

For logging and for pubsub, it seems like grouping the requests is required of the bundler, since individual request messages can be directed towards different topics or logs. If we want to make a generic solution in toolkit, I think we have to support that.

Not sure if the suggestion is to hold off on the bundler or the grouping itself. Without the grouping, the bundler will not really be improving throughput.

It should be possible to include the grouping logic in the client based on this generic implementation, so I'm mocking that now. LMK if I'm misunderstanding.

**Comment by jba** [comment]
Sai, I may the one who is misunderstanding, but Michael's point (which I
agree with) is this:

We only have two use cases for bundling, logging and pubsub. Both have
custom clients. Both those clients are already designed with a separate
type that corresponds to a group. E.g. in logging, you create one or more
Loggers, where each Logger is a group. Since grouping is already done by
the clients, there is no compelling reason to add it to the bundler.

Even without grouping, a bundler can improve throughput by amortizing the
fixed costs of an RPC over many items. If I am logging very quickly to the
same Logger, it should be more efficient to send fewer RPCs each with
several log entries.

Also, FWIW, I think most users will only need one group. They'll log to one
log, or publish to one topic.

So I recommend, and I think Michael would agree, that you not implement
grouping in gax.

**Comment by saicheems** [comment]
OK, that makes sense, and I agree.

**Comment by mcgreevy** [comment]
Yes, thanks Jonathan, that captures my position well.

**Pull request closed without merging**
